esphome:
  name: ld2420

esp8266:
  board: esp12e

# Enable logging
logger:
  level: INFO
# Enable Home Assistant API
api:
  encryption:
    key: ""
  batch_delay: 0ms

ota:
  - platform: esphome
    password: ""

uart:
  tx_pin: GPIO4
  rx_pin: GPIO14
  baud_rate: 115200
  parity: NONE
  rx_buffer_size: 2048
  stop_bits: 1
  id: uart_a

ld2420:

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence
      #filters:
      #  - settle: 1s

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    gate_move_sensitivity:
      name: Gate Move Sensitivity
    gate_still_sensitivity:
      name: Gate Still Sensitivity
        gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value

button:
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 
  ap:
    ssid: "ld2420-fallback"
    password: ""

captive_portal:
