esphome:
  name: leak-detector
  friendly_name: leak-detector

esp8266:
  board: esp12e
  restore_from_flash: True

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

sensor:
  - platform: adc
    pin: GPIO17
    id: detector_input
    name: "Leak detector analog input"
    update_interval: 10s
    on_value:
      then:
        - lambda: |-
            if( x > 1.1 ){
              id(leak_alert).publish_state(true);
            }
            else {
              id(leak_alert).publish_state(false);
            }

binary_sensor:
  - platform: template
    id: leak_alert
    name: "Leak Alert"
    device_class: safety
    on_state:
      then:
        if:
          condition:
            - binary_sensor.is_on: leak_alert
          then:
            - switch.turn_on: sleep_inhibit
            - logger.log: "Leak Alert: Sleep inhibited"

switch:
  - platform: homeassistant
    id: sleep_inhibit
    entity_id: input_boolean.leak_sleep_inhibit
    name: "Sleep inhibit"
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - deep_sleep.prevent: id_sleep
        - logger.log: "Sleep Inhibit: Enabled"
    on_turn_off:
      then:
        - deep_sleep.allow: id_sleep
        - logger.log: "Sleep Inhibit: Disabled"

deep_sleep:
  run_duration: 30s
  sleep_duration: 5min
  id: id_sleep

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 

  ap:
    ssid: "Leak-Detector Fallback Hotspot"
    password: ""


captive_portal:
